		/* Latest News */
		function getDataByCategoryName(t,e,s){var l="https://www.kunal-chowdhury.com/feeds/posts/summary/-/"+t+"?published&alt=json&max-results="+s,a=new XMLHttpRequest();a.open("GET",l,true),a.onload=function(){if(this.status>=200&&this.status<400){var t=JSON.parse(this.response),s='<ul class="recent-posts-ul">';t.feed.entry.forEach(function(t,e){for(var l,a=t.title.$t,n=0;n<t.link.length;n++)if("alternate"==t.link[n].rel){l=t.link[n].href;break}s+='<li class="recent-posts-ul-li"><div class="recent-posts-ul-li-div"><a class="recent-posts-ul-li-div-a" href="'+l+'" alt="'+a+'" title="'+a+'">'+a+"</a></div></li>"}),s+="</ul>";var e1=document.getElementById(e);if(e1!=null){e1.insertAdjacentHTML("afterend",s);}}},a.send();}
		function LoadTechNewsWidget(){getDataByCategoryName('Tech News','latestTechNews',5);}
        
        /* Lazy Load Images */
        function LazyLoadImages(){var e;if("IntersectionObserver" in window){e=document.querySelectorAll(".lazy");if(e.length==0){return;}var n=new IntersectionObserver(function(e,t){e.forEach(function(e){if(e.isIntersecting){var t=e.target;t.src=t.dataset.src,t.classList.remove("lazy"),n.unobserve(t)}})});e.forEach(function(e){n.observe(e)})}else{var t;function r(){t&&clearTimeout(t),t=setTimeout(function(){var n=window.pageYOffset;e.forEach(function(e){e.offsetTop<window.innerHeight+n&&(e.src=e.dataset.src,e.classList.remove("lazy"))}),0==e.length&&(document.removeEventListener("scroll",r),window.removeEventListener("resize",r),window.removeEventListener("orientationChange",r))},20)}e=document.querySelectorAll(".lazy");if(e.length==0){return;}document.addEventListener("scroll",r),window.addEventListener("resize",r),window.addEventListener("orientationChange",r)}};
        
        /* Lazy Load YouTube Videos */
        function LazyLoadYouTubeVideos(){var e=document.querySelectorAll(".youtube");if(e.length==0){return;};for(t=0;t<e.length;t++){var r="https://img.youtube.com/vi/"+e[t].dataset.embed+"/hqdefault.jpg",a=new Image;a.src=r,a.alt='Click to play the Youtube Video',a.title='Click to play the Youtube Video',a.addEventListener("load",void e[t].appendChild(a)),e[t].addEventListener("click",function(){var e=document.createElement("iframe");e.setAttribute("frameborder","0"),e.setAttribute("allowfullscreen",""),e.setAttribute("src","https://www.youtube.com/embed/"+this.dataset.embed+"?rel=0&showinfo=0&autoplay=1"),this.innerHTML="",this.appendChild(e)})}}
        
        /* URL Rewrite */
		function UrlRewrite(){setTimeout(function(){var o,t,c=Math.floor(Date.now()),e=document.querySelector("link[rel='canonical']").href,n=e+(e.includes("?")?"&ts=":"?ts=")+c+"&pos="+window.scrollY,r="";c%2==0&&(o="Google",t="organic",r="https://www.google.com"),c%3==0&&(o="twitter.com",t="social",r="https://twitter.com"),c%5==0&&(o="DuckDuckGo",t="organic",r="https://duckduckgo.com"),c%7==0&&(o="codeproject.com",t="referral",r="https://www.codeproject.com"),c%11==0&&(o="dzone.com",t="social",r="https://dzone.com"),c%13==0&&(o="Bing",t="organic",r="https://www.bing.com"),c%17==0&&(o="facebook.com",t="social",r="https://www.facebook.com"),c%19==0&&(o="linkedin.com",t="social",r="https://www.linkedin.com"),c%23==0&&(o="dotnetkicks.com",t="referral",r="http://dotnetkicks.com"),null==o||""==o?window.location.href=n:(Object.defineProperty(document,"referrer",{get:function(){return r}}),window.location.href=n+"&utm_source="+o+"&utm_medium="+t)},240000)}